/**
 * Embeds dist/public/index.html into server/embedded-index.ts so the serverless
 * function can serve the SPA HTML without reading from the filesystem (public/
 * is not available in Vercel's function bundle).
 */
import { readFile, writeFile } from "fs/promises";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, "..");
const indexPath = path.join(rootDir, "dist", "public", "index.html");
const outPath = path.join(rootDir, "server", "embedded-index.ts");

const html = await readFile(indexPath, "utf-8");
const content = `// Generated by script/embed-html.ts - do not edit
export const embeddedIndexHtml = ${JSON.stringify(html)};
`;

await writeFile(outPath, content, "utf-8");
console.log("embedded index.html into server/embedded-index.ts");
